export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  DOCUMENTS: "/dashboard/documents",
  CHAT: "/dashboard/chat",
  CHAT_DOCUMENT: (contentId: string) => `/dashboard/chat/${contentId}`,
  WORKSPACE: (contentId: string) => `/dashboard/workspace/${contentId}`,
  NOTES: "/dashboard/notes",
  QUIZ: "/dashboard/quiz",
  FLASHCARDS: "/dashboard/flashcards",
  STUDY_PLANNER: "/dashboard/study-planner",
  STUDY_PLANNER_DOCUMENT: (contentId: string) => `/dashboard/study-planner/${contentId}`,
  SETTINGS: "/dashboard/settings",
} as const;
